import { uniq } from 'lodash'

// 弦品与音符
const NoteNameMap = {
  100: 'E',
  101: 'F',
  102: 'F#',
  103: 'G',
  104: 'G#',
  105: 'A',
  106: 'A#',
  107: 'B',
  108: 'C',
  109: 'C#',
  110: 'D',
  111: 'D#',
  112: 'E',
  113: 'F',
  114: 'F#',
  115: 'G',
  200: 'B',
  201: 'C',
  202: 'C#',
  203: 'D',
  204: 'D#',
  205: 'E',
  206: 'F',
  207: 'F#',
  208: 'G',
  209: 'G#',
  210: 'A',
  211: 'A#',
  212: 'B',
  213: 'C',
  214: 'C#',
  215: 'D',
  300: 'G',
  301: 'G#',
  302: 'A',
  303: 'A#',
  304: 'B',
  305: 'C',
  306: 'C#',
  307: 'D',
  308: 'D#',
  309: 'E',
  310: 'F',
  311: 'F#',
  312: 'G',
  313: 'G#',
  314: 'A',
  315: 'A#',
  400: 'D',
  401: 'D#',
  402: 'E',
  403: 'F',
  404: 'F#',
  405: 'G',
  406: 'G#',
  407: 'A',
  408: 'A#',
  409: 'B',
  410: 'C',
  411: 'C#',
  412: 'D',
  413: 'D#',
  414: 'E',
  415: 'F',
  500: 'A',
  501: 'A#',
  502: 'B',
  503: 'C',
  504: 'C#',
  505: 'D',
  506: 'D#',
  507: 'E',
  508: 'F',
  509: 'F#',
  510: 'G',
  511: 'G#',
  512: 'A',
  513: 'A#',
  514: 'B',
  515: 'C',
  600: 'E',
  601: 'F',
  602: 'F#',
  603: 'G',
  604: 'G#',
  605: 'A',
  606: 'A#',
  607: 'B',
  608: 'C',
  609: 'C#',
  610: 'D',
  611: 'D#',
  612: 'E',
  613: 'F',
  614: 'F#',
  615: 'G'
}

// 音符与和弦
const ChordNameMap = {
  'C|E|G': 'C',
  'C#|F|G#': 'C#',
  'D|F#|A': 'D',
  'D#|G|A#': 'D#',
  'E|G#|B': 'E',
  'F|A|C': 'F',
  'F#|A#|C#': 'F#',
  'G|B|D': 'G',
  'G#|C|D#': 'G#',
  'A|C#|E': 'A',
  'A#|D|F': 'A#',
  'B|D#|F#': 'B',
  'C|D#|G': 'Cm',
  'C#|E|G#': 'C#m',
  'D|F|A': 'Dm',
  'D#|F#|A#': 'D#m',
  'E|G|B': 'Em',
  'F|G#|C': 'Fm',
  'F#|A|C#': 'F#m',
  'G|A#|D': 'Gm',
  'G#|B|D#': 'G#m',
  'A|C|E': 'Am',
  'A#|C#|F': 'A#m',
  'B|D|F#': 'Bm',
  'C|D|G': 'Csus2',
  'C#|D#|G#': 'C#sus2',
  'D|E|A': 'Dsus2',
  'D#|F|A#': 'D#sus2',
  'E|F#|B': 'Esus2',
  'F|G|C': 'Fsus2',
  'F#|G#|C#': 'F#sus2',
  'G|A|D': 'Gsus2',
  'G#|A#|D#': 'G#sus2',
  'A|B|E': 'Asus2',
  'A#|C|F': 'A#sus2',
  'B|C#|F#': 'Bsus2',
  'C|F|G': 'Csus4',
  'C#|F#|G#': 'C#sus4',
  'D|G|A': 'Dsus4',
  'D#|G#|A#': 'D#sus4',
  'E|A|B': 'Esus4',
  'F|A#|C': 'Fsus4',
  'F#|B|C#': 'F#sus4',
  'G|C|D': 'Gsus4',
  'G#|C#|D#': 'G#sus4',
  'A|D|E': 'Asus4',
  'A#|D#|F': 'A#sus4',
  'B|E|F#': 'Bsus4',
  'C|D#|F#': 'Cdim',
  'C#|E|G': 'C#dim',
  'D|F|G#': 'Ddim',
  'D#|F#|A': 'D#dim',
  'E|G|A#': 'Edim',
  'F|G#|B': 'Fdim',
  'F#|A|C': 'F#dim',
  'G|A#|C#': 'Gdim',
  'G#|B|D': 'G#dim',
  'A|C|D#': 'Adim',
  'A#|C#|E': 'A#dim',
  'B|D|F': 'Bdim',
  'C|E|G#': 'Caug',
  'C#|F|A': 'C#aug',
  'D|F#|A#': 'Daug',
  'D#|G|B': 'D#aug',
  'E|G#|C': 'Eaug',
  'F|A|C#': 'Faug',
  'F#|A#|D': 'F#aug',
  'G|B|D#': 'Gaug',
  'G#|C|E': 'G#aug',
  'A|C#|F': 'Aaug',
  'A#|D|F#': 'A#aug',
  'B|D#|G': 'Baug',
  'C|E|G|B': 'Cmaj7',
  'C#|F|G#|C': 'C#maj7',
  'D|F#|A|C#': 'Dmaj7',
  'D#|G|A#|D': 'D#maj7',
  'E|G#|B|D#': 'Emaj7',
  'F|A|C|E': 'Fmaj7',
  'F#|A#|C#|F': 'F#maj7',
  'G|B|D|F#': 'Gmaj7',
  'G#|C|D#|G': 'G#maj7',
  'A|C#|E|G#': 'Amaj7',
  'A#|D|F|A': 'A#maj7',
  'B|D#|F#|A#': 'Bmaj7',
  'C|E|G|A#': 'C7',
  'C#|F|G#|B': 'C#7',
  'D|F#|A|C': 'D7',
  'D#|G|A#|C#': 'D#7',
  'E|G#|B|D': 'E7',
  'F|A|C|D#': 'F7',
  'F#|A#|C#|E': 'F#7',
  'G|B|D|F': 'G7',
  'G#|C|D#|F#': 'G#7',
  'A|C#|E|G': 'A7',
  'A#|D|F|G#': 'A#7',
  'B|D#|F#|A': 'B7',
  'C|D#|G|B': 'Cm(maj7)',
  'C#|E|G#|C': 'C#m(maj7)',
  'D|F|A|C#': 'Dm(maj7)',
  'D#|F#|A#|D': 'D#m(maj7)',
  'E|G|B|D#': 'Em(maj7)',
  'F|G#|C|E': 'Fm(maj7)',
  'F#|A|C#|F': 'F#m(maj7)',
  'G|A#|D|F#': 'Gm(maj7)',
  'G#|B|D#|G': 'G#m(maj7)',
  'A|C|E|G#': 'Am(maj7)',
  'A#|C#|F|A': 'A#m(maj7)',
  'B|D|F#|A#': 'Bm(maj7)',
  'C|D#|G|A#': 'Cm7',
  'C#|E|G#|B': 'C#m7',
  'D|F|A|C': 'Dm7',
  'D#|F#|A#|C#': 'D#m7',
  'E|G|B|D': 'Em7',
  'F|G#|C|D#': 'Fm7',
  'F#|A|C#|E': 'F#m7',
  'G|A#|D|F': 'Gm7',
  'G#|B|D#|F#': 'G#m7',
  'A|C|E|G': 'Am7',
  'A#|C#|F|G#': 'A#m7',
  'B|D|F#|A': 'Bm7',
  'C|D|G|B': 'Cmaj7sus2',
  'C#|D#|G#|C': 'C#maj7sus2',
  'D|E|A|C#': 'Dmaj7sus2',
  'D#|F|A#|D': 'D#maj7sus2',
  'E|F#|B|D#': 'Emaj7sus2',
  'F|G|C|E': 'Fmaj7sus2',
  'F#|G#|C#|F': 'F#maj7sus2',
  'G|A|D|F#': 'Gmaj7sus2',
  'G#|A#|D#|G': 'G#maj7sus2',
  'A|B|E|G#': 'Amaj7sus2',
  'A#|C|F|A': 'A#maj7sus2',
  'B|C#|F#|A#': 'Bmaj7sus2',
  'C|D|G|A#': 'C7sus2',
  'C#|D#|G#|B': 'C#7sus2',
  'D|E|A|C': 'D7sus2',
  'D#|F|A#|C#': 'D#7sus2',
  'E|F#|B|D': 'E7sus2',
  'F|G|C|D#': 'F7sus2',
  'F#|G#|C#|E': 'F#7sus2',
  'G|A|D|F': 'G7sus2',
  'G#|A#|D#|F#': 'G#7sus2',
  'A|B|E|G': 'A7sus2',
  'A#|C|F|G#': 'A#7sus2',
  'B|C#|F#|A': 'B7sus2',
  'C|F|G|B': 'Cmaj7sus4',
  'C#|F#|G#|C': 'C#maj7sus4',
  'D|G|A|C#': 'Dmaj7sus4',
  'D#|G#|A#|D': 'D#maj7sus4',
  'E|A|B|D#': 'Emaj7sus4',
  'F|A#|C|E': 'Fmaj7sus4',
  'F#|B|C#|F': 'F#maj7sus4',
  'G|C|D|F#': 'Gmaj7sus4',
  'G#|C#|D#|G': 'G#maj7sus4',
  'A|D|E|G#': 'Amaj7sus4',
  'A#|D#|F|A': 'A#maj7sus4',
  'B|E|F#|A#': 'Bmaj7sus4',
  'C|F|G|A#': 'C7sus4',
  'C#|F#|G#|B': 'C#7sus4',
  'D|G|A|C': 'D7sus4',
  'D#|G#|A#|C#': 'D#7sus4',
  'E|A|B|D': 'E7sus4',
  'F|A#|C|D#': 'F7sus4',
  'F#|B|C#|E': 'F#7sus4',
  'G|C|D|F': 'G7sus4',
  'G#|C#|D#|F#': 'G#7sus4',
  'A|D|E|G': 'A7sus4',
  'A#|D#|F|G#': 'A#7sus4',
  'B|E|F#|A': 'B7sus4',
  'C|E|G|A': 'C6',
  'C#|F|G#|A#': 'C#6',
  'D|F#|A|B': 'D6',
  'D#|G|A#|C': 'D#6',
  'E|G#|B|C#': 'E6',
  'F|A|C|D': 'F6',
  'F#|A#|C#|D#': 'F#6',
  'G|B|D|E': 'G6',
  'G#|C|D#|F': 'G#6',
  'A|C#|E|F#': 'A6',
  'A#|D|F|G': 'A#6',
  'B|D#|F#|G#': 'B6',
  'C|F|G|A': 'Cm6',
  'C#|F#|G#|A#': 'C#m6',
  'D|G|A|B': 'Dm6',
  'D#|G#|A#|C': 'D#m6',
  'E|A|B|C#': 'Em6',
  'F|A#|C|D': 'Fm6',
  'F#|B|C#|D#': 'F#m6',
  'G|C|D|E': 'Gm6',
  'G#|C#|D#|F': 'G#m6',
  'A|D|E|F#': 'Am6',
  'A#|D#|F|G': 'A#m6',
  'B|E|F#|G#': 'Bm6',
  'C|E|G#|B': 'Cmaj7(#5)',
  'C#|F|A|C': 'C#maj7(#5)',
  'D|F#|A#|C#': 'Dmaj7(#5)',
  'D#|G|B|D': 'D#maj7(#5)',
  'E|G#|C|D#': 'Emaj7(#5)',
  'F|A|C#|E': 'Fmaj7(#5)',
  'F#|A#|D|F': 'F#maj7(#5)',
  'G|B|D#|F#': 'Gmaj7(#5)',
  'G#|C|E|G': 'G#maj7(#5)',
  'A|C#|F|G#': 'Amaj7(#5)',
  'A#|D|F#|A': 'A#maj7(#5)',
  'B|D#|G|A#': 'Bmaj7(#5)',
  'C|D#|F#|A#': 'C∅',
  'C#|E|G|B': 'C#∅',
  'D|F|G#|C': 'D∅',
  'D#|F#|A|C#': 'D#∅',
  'E|G|A#|D': 'E∅',
  'F|G#|B|D#': 'F∅',
  'F#|A|C|E': 'F#∅',
  'G|A#|C#|F': 'G∅',
  'G#|B|D|F#': 'G#∅',
  'A|C|D#|G': 'A∅',
  'A#|C#|E|G#': 'A#∅',
  'B|D|F|A': 'B∅',
  'C|D#|F#|A': 'Cdim7',
  'C#|E|G|A#': 'C#dim7',
  'D|F|G#|B': 'Ddim7',
  'D#|F#|A|C': 'D#dim7',
  'E|G|A#|C#': 'Edim7',
  'F|G#|B|D': 'Fdim7',
  'F#|A|C|D#': 'F#dim7',
  'G|A#|C#|E': 'Gdim7',
  'G#|B|D|F': 'G#dim7',
  'A|C|D#|F#': 'Adim7',
  'A#|C#|E|G': 'A#dim7',
  'B|D|F|G#': 'Bdim7',
  'C|G': 'C5',
  'C#|G#|': 'C#5',
  'D|A|': 'D5',
  'D#|A#|': 'D#5',
  'E|B|': 'E5',
  'F|C|': 'F5',
  'F#|C#|': 'F#5',
  'G|D|': 'G5',
  'G#|D#|': 'G#5',
  'A|E|': 'A5',
  'A#|F|': 'A#5',
  'B|F#|': 'B5',
  'C|D|E|G': 'Cadd9',
  'C#|D#|F|G#': 'C#add9',
  'D|E|F#|A': 'Dadd9',
  'D#|F|G|A#': 'D#add9',
  'E|F#|G#|B': 'Eadd9',
  'F|G|A|C': 'Fadd9',
  'F#|G#|A#|C#': 'F#add9',
  'G|A|B|D': 'Gadd9',
  'G#|A#|C|D#': 'G#add9',
  'A|B|C#|E': 'Aadd9',
  'A#|C|D|F': 'A#add9',
  'B|C#|D#|F#': 'Badd9'
}

/**
 * 获取排序
 */
function getOrder(root: string): string[] {
  const oList = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
  const index = oList.indexOf(root)
  const spliceArr = oList.splice(index)

  return spliceArr.concat(oList)
}

/**
 * 重排
 */
function reoreder(root, notes) {
  const list = getOrder(root)

  const arr: string[] = []
  notes.map((note) => {
    const index = list.indexOf(note)
    arr[index] = note
  })

  return arr.filter((s) => s && s.trim())
}

/**
 * 获取和弦名称
 * @param {number} string - 弦
 * @param {number} fret - 品
 */
export default function getChordName(data: any): string {
  let arr: string[] = []

  data.map((item) => {
    const { string, fret } = item
    const val = string * 100 + fret
    const name = NoteNameMap[val]

    arr.push(name)
  })

  arr = reoreder(arr[0], uniq(arr))

  return ChordNameMap[arr.join('|')] || ''
}
